stages:
  - test
  - deploy

matrix:
  include:
    - stage: test
      os: linux
      env: SCRIPT=ubuntu WITH_CORE_LIBRARY=yes
      services: docker
    - stage: test
      os: linux
      env: SCRIPT=ubuntu
      services: docker
    - stage: test
      os: linux
      env: SCRIPT=debian WITH_CORE_LIBRARY=yes
      services: docker
    - stage: test
      os: linux
      env: SCRIPT=debian
      services: docker
    - stage: test
      os: linux
      env: SCRIPT=fedora WITH_CORE_LIBRARY=yes
      services: docker
    - stage: test
      os: linux
      env: SCRIPT=fedora
      services: docker
    - stage: test
      os: osx
      env: SCRIPT=osx WITH_CORE_LIBRARY=yes
    - stage: test
      os: osx
      env: SCRIPT=osx
    - if: branch IN (master, develop)
      stage: deploy
      os: linux
      env: SCRIPT=manylinux2010 BINARY_PACKAGE=yes
      language: python
      python: 3.5
    - if: branch IN (master, develop)
      stage: deploy
      os: linux
      env: SCRIPT=manylinux2010 BINARY_PACKAGE=yes
      language: python
      python: 3.6
    - if: branch IN (master, develop)
      stage: deploy
      os: linux
      env: SCRIPT=sdist
      language: python
      python: 3.6

script:
  - $TRAVIS_BUILD_DIR/.travis/${SCRIPT}.sh

deploy:
  skip_cleanup: true
  provider: script
  script:
    - $TRAVIS_BUILD_DIR/.travis/deploy.sh
  on:
    tags: false
    condition: $TRAVIS_BUILD_STAGE_NAME = Deploy
    branch:
      - develop
      - master
