stages:
  - test
  - deploy

matrix:
  include:
    - stage: test
      os: linux
      env: SCRIPT=ubuntu WITH_CORE_LIBRARY=yes
      services: docker
    - stage: test
      os: linux
      env: SCRIPT=ubuntu
      services: docker
    - stage: test
      os: linux
      env: SCRIPT=debian WITH_CORE_LIBRARY=yes
      services: docker
    - stage: test
      os: linux
      env: SCRIPT=debian
      services: docker
    - stage: test
      os: linux
      env: SCRIPT=fedora WITH_CORE_LIBRARY=yes
      services: docker
    - stage: test
      os: linux
      env: SCRIPT=fedora
      services: docker
    - stage: test
      os: osx
      env: SCRIPT=osx WITH_CORE_LIBRARY=yes
    - stage: test
      os: osx
      env: SCRIPT=osx
    - if: branch = develop
      stage: deploy
      os: linux
      language: python
      python: 3.5
      script:
        - export PRIMITIV_PYTHON_BUILD_NUMBER="dev${TRAVIS_BUILD_NUMBER}"
        - pip install cython numpy scikit-build twine
        - wget "http://bitbucket.org/eigen/eigen/get/3.3.4.tar.bz2" -O eigen-downloaded.tar.gz
        - mkdir ./eigen-downloaded
        - tar xf ./eigen-downloaded.tar.gz --strip-components=1 -C ./eigen-downloaded
        - $TRAVIS_BUILD_DIR/setup.py sdist --bundle-core-library --bundle-eigen-headers ./eigen-downloaded
        - pip install $TRAVIS_BUILD_DIR/dist/primitiv-*.tar.gz
        - mkdir ./work
        - pushd ./work
        - python -c "import primitiv; dev = primitiv.devices.Eigen()"
        - popd
      deploy:
        skip_cleanup: true
        provider: script
        script: twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD $TRAVIS_BUILD_DIR/dist/primitiv-*.tar.gz
        on:
          tags: false
          branch: develop
    - if: branch = master
      stage: deploy
      os: linux
      language: python
      python: 3.5
      script:
        - export PRIMITIV_PYTHON_BUILD_NUMBER="${TRAVIS_BUILD_NUMBER}"
        - pip install cython numpy scikit-build twine
        - wget "http://bitbucket.org/eigen/eigen/get/3.3.4.tar.bz2" -O eigen-downloaded.tar.gz
        - mkdir ./eigen-downloaded
        - tar xf ./eigen-downloaded.tar.gz --strip-components=1 -C ./eigen-downloaded
        - $TRAVIS_BUILD_DIR/setup.py sdist --bundle-core-library --bundle-eigen-headers ./eigen-downloaded
        - pip install $TRAVIS_BUILD_DIR/dist/primitiv-*.tar.gz
        - mkdir ./work
        - pushd ./work
        - python -c "import primitiv; dev = primitiv.devices.Eigen()"
        - popd
      deploy:
        skip_cleanup: true
        provider: script
        script: twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD $TRAVIS_BUILD_DIR/dist/primitiv-*.tar.gz
        on:
          tags: false
          branch: master

script:
  - $TRAVIS_BUILD_DIR/.travis/${SCRIPT}.sh
